# configs/main_config.yaml

run_name: "french_experiment_gemma"
model_name: "gemma-2-9b" # 1.2 B multilignual model, 512 seq length
d_model: 3584 # 3584 for gemma-2-9b

device: "cpu"
cache_activations: True
seed: "42"

layers: [20] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    config_name: "linear_mean"
  - name: "linear"
    config_name: "linear_max"
  - name: "linear"
    config_name: "linear_last"
  - name: "linear"
    config_name: "linear_softmax"
  - name: "attention"
    config_name: "default_attention"
  - name: "mass_mean"
    config_name: "default_mass_mean"

# List of experiments to run
experiments:
  - name: 1-french-pred-auc
    metric: auc
    class_names: {0: "English", 1: "French"}
    train_on: 91_eng-french
    evaluate_on:
      - 91_eng-french
    score:
      - all
      - filtered
  - name: 2-french-pred-auc-increasing-french-fixed-total
    metric: auc
    class_names: {0: "English", 1: "French"}
    train_on: 91_eng-french
    evaluate_on:
      - 91_eng-french
    score:
      - all
      - filtered
    rebuild_config:
      increasing_french_fixed_total:
        - {class_counts: {0: 3998, 1: 2}, seed: 42}
        - {class_counts: {0: 3995, 1: 5}, seed: 42}
        - {class_counts: {0: 3990, 1: 10}, seed: 42}
        - {class_counts: {0: 3980, 1: 20}, seed: 42}
        - {class_counts: {0: 3965, 1: 35}, seed: 42}
        - {class_counts: {0: 3950, 1: 50}, seed: 42}
        - {class_counts: {0: 3900, 1: 100}, seed: 42}
        - {class_counts: {0: 3850, 1: 150}, seed: 42}
        - {class_counts: {0: 3750, 1: 250}, seed: 42}
        - {class_counts: {0: 3500, 1: 500}, seed: 42}
        - {class_counts: {0: 3250, 1: 750}, seed: 42}
  - name: 3-french-pred-auc-llm-upsampling
    metric: auc
    class_names: {0: "English", 1: "French"}
    train_on: 91_eng-french
    evaluate_on:
      - 91_eng-french
    score:
      - all
      - filtered
    rebuild_config:
      increasing_french_fixed_total:
        - {class_counts: {0: 3998, 1: 2}, llm_upsample: False, seed: 42}
        - {class_counts: {0: 3995, 1: 5}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3990, 1: 10}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3980, 1: 20}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3965, 1: 35}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3950, 1: 50}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3900, 1: 100}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3850, 1: 150}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3750, 1: 250}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3500, 1: 500}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3250, 1: 750}, llm_upsample: True, seed: 42}
  # - name: 4-french-pred-contrast-auc
  #   metric: auc
  #   class_names: {0: "English", 1: "French"}
  #   train_on: 91_eng-french
  #   evaluate_on:
  #     - 91_eng-french
  #   score:
  #     - all
  #     - filtered
  #   rebuild_config:
  #     increasing_french_fixed_total:
  #       - {class_counts: {0: 3998, 1: 2}, seed: 42}
  #       - {class_counts: {0: 3995, 1: 5}, seed: 42}
  #       - {class_counts: {0: 3990, 1: 10}, seed: 42}
  #       - {class_counts: {0: 3980, 1: 20}, seed: 42}
  #       - {class_counts: {0: 3965, 1: 35}, seed: 42}
  #       - {class_counts: {0: 3950, 1: 50}, seed: 42}
  #       - {class_counts: {0: 3900, 1: 100}, seed: 42}
  #       - {class_counts: {0: 3850, 1: 150}, seed: 42}
  #       - {class_counts: {0: 3750, 1: 250}, seed: 42}
  #       - {class_counts: {0: 3500, 1: 500}, seed: 42}
  #       - {class_counts: {0: 3250, 1: 750}, seed: 42}

model_check:
  - name: french-pred
    hf_model_name: "google/gemma-2-9b-it"
    check_on: "91_eng-french"
    check_prompt: "In one word, the statement '{prompt}' is in the language of:"
    class_names: {0: "English", 1: "French"}

