# configs/main_config.yaml

run_name: "french_experiment_gemma"
model_name: "gemma-2-9b" # 1.2 B multilignual model, 512 seq length
device: "cuda:1"
cache_activations: True
seed: "42"

layers: [20] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    aggregation: "mean"
    config_name: "default_linear"
  - name: "attention"
    aggregation: "attention"
    config_name: "default_attention"

# List of experiments to run
experiments:
  - name: eng_french_language-auc
    metric: auc
    class_names: {0: "English", 1: "French"}
    train_on: 91_eng-french
    evaluate_on:
      - 91_eng-french
    score:
      - all
    rebuild_config:
      constant_french_increasing_english:
        - {class_counts: {0: 50, 1: 50}, seed: 42}
        - {class_counts: {0: 500, 1: 50}, seed: 42}
        - {class_counts: {0: 1500, 1: 50}, seed: 42}
        - {class_counts: {0: 3000, 1: 50}, seed: 42}
        - {class_counts: {0: 5000, 1: 50}, seed: 42}
        - {class_counts: {0: 7000, 1: 50}, seed: 42}
      constant_percent_french_increasing_total:
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 100, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 550, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 1550, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 3050, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 5050, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 7050, seed: 42}
  - name: eng_french_language-fpr-recall
    metric: fpr_recall
    class_names: {0: "English", 1: "French"}
    train_on: 91_eng-french
    evaluate_on:
      - 91_eng-french
    score:
      - all
    rebuild_config:
      constant_french_increasing_english:
        - {class_counts: {0: 50, 1: 50}, seed: 42}
        - {class_counts: {0: 500, 1: 50}, seed: 42}
        - {class_counts: {0: 1500, 1: 50}, seed: 42}
        - {class_counts: {0: 3000, 1: 50}, seed: 42}
        - {class_counts: {0: 5000, 1: 50}, seed: 42}
        - {class_counts: {0: 7000, 1: 50}, seed: 42}
      constant_percent_french_increasing_total:
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 100, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 550, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 1550, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 3050, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 5050, seed: 42}
        - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 7050, seed: 42}

model_check:
  - name: french-pred
    hf_model_name: "google/gemma-2-9b-it"
    check_on: "91_eng-french"
    check_prompt: 'In one word, the statement "{prompt}" is in the language of:'
    class_names: {0: "English", 1: "French"}

