# configs/main_config.yaml

run_name: "french_experiment_gemma"
model_name: "gemma-2-9b" # 1.2 B multilignual model, 512 seq length
device: "cuda:1"
cache_activations: True
seed: "42"

layers: [20] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    aggregation: "last"
    config_name: "default_linear"
  - name: "attention"
    aggregation: "attention"
    config_name: "default_attention"

# List of experiments to run
experiments:
  - name: eng_french_language
    class_names: {0: "English", 1: "French"} # only if train_on and evaluate_on are same
    train_on: 91_eng-french
    evaluate_on:
      - 91_eng-french
    score:
      - all
      # - filtered # don't need to filter here since only 1-2 are unsure (but could add threshold)
    rebuild_config: # tests on imbalanced data, evals (test + val) on balanced data
      constant_french_increasing_english:
        - {class_counts: {0: 50, 1: 50}, seed: 42} 
        - {class_counts: {0: 500, 1: 50}, seed: 42}     # 0 is French, 1 is English
        - {class_counts: {0: 1500, 1: 50}, seed: 42}
        - {class_counts: {0: 3000, 1: 50}, seed: 42}
        - {class_counts: {0: 5000, 1: 50}, seed: 42}
        - {class_counts: {0: 7000, 1: 50}, seed: 42}
        # - {class_counts: {0: 10000, 1: 50}, seed: 42}

      constant_percent_french_increasing_total:
        - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 100, seed: 42}
        - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 550, seed: 42}
        - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 1550, seed: 42}
        - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 3050, seed: 42}
        - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 5050, seed: 42}
        - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 7050, seed: 42}
        # - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 10050, seed: 42}
      # constant_total_increasing_percent_french:
      #   - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 5050, seed: 42}
      #   - {class_percents: {0: 0.75, 1: 0.25}, total_samples: 5050, seed: 42}
      #   - {class_percents: {0: 0.5, 1: 0.5}, total_samples: 5050, seed: 42}
      #   - {class_percents: {0: 0.25, 1: 0.75}, total_samples: 5050, seed: 42}
      #   - {class_percents: {0: 0.1, 1: 0.9}, total_samples: 5050, seed: 42}

model_check:
  - name: french-pred
    hf_model_name: "google/gemma-2-9b-it"
    check_on: "91_eng-french"
    check_prompt: 'In one word, the statement "{prompt}" is in the language of:'
    class_names: {0: "English", 1: "French"}

