# configs/main_config.yaml

run_name: "french_probing"
model_name: "ai-forever/mGPT" # 1.2 B multilignual model, 512 seq length
device: "cuda:1"
cache_activations: True
seed: "42"

# Define the layers and components to extract activations from
layers: [13] # 24 layers
components:
  - "resid_post"

# Define the probe architectures and their hyperparameter configs.
architectures:
  - name: "linear"
    config_name: "default_linear"
  - name: "attention"
    config_name: "default_attention"

# Define the score aggregation methods to test for each architecture
aggregations:
  - "mean"

# List of experiments to run
experiments:
  - name: french_questions
    train_on: 90_french_truthqa_tf
    evaluate_on:
      - 90_french_truthqa_tf
      - 91_eng-french
      - 33_truthqa_tf

  - name: eng_french_language
    train_on: 91_eng-french
    evaluate_on:
      - 90_french_truthqa_tf
      - 91_eng-french
      - 33_truthqa_tf

  - name: english_questions
    train_on: 33_truthqa_tf
    evaluate_on:
      - 90_french_truthqa_tf
      - 91_eng-french
      - 33_truthqa_tf

