# configs/main_config.yaml

run_name: "french_experiment_gemma"
model_name: "gemma-2-9b" # 1.2 B multilignual model, 512 seq length
device: "cuda:1"
cache_activations: True
seed: "42"

layers: [20] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    aggregation: "last"
    config_name: "default_linear"
  - name: "attention"
    aggregation: "attention"
    config_name: "default_attention"

# List of experiments to run
experiments:
  - name: eng_french_language
    train_on: 91_eng-french
    evaluate_on:
      - 91_eng-french
    score:
      - all
      # - filtered # don't need to filter here since only 1-2 are unsure (but could add threshold)
    rebuild_config:
      # 1. Constant number of French samples, increasing English samples
      - {class_counts: {0: 50, 1: 50}, seed: 42} 
      - {class_counts: {0: 50, 1: 500}, seed: 42}     # 0 is English, 1 is French
      - {class_counts: {0: 50, 1: 1000}, seed: 42}
      - {class_counts: {0: 50, 1: 1500}, seed: 42}
      - {class_counts: {0: 50, 1: 2000}, seed: 42}

      # 2. Constant percent French, increasing total samples
      - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 100, seed: 42}
      - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 550, seed: 42}
      - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 1050, seed: 42}
      - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 1550, seed: 42}
      - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 2050, seed: 42}

      # 3. Constant total samples, increasing percent French
      - {class_percents: {0: 0.9, 1: 0.1}, total_samples: 2050, seed: 42}
      - {class_percents: {0: 0.75, 1: 0.25}, total_samples: 2050, seed: 42}
      - {class_percents: {0: 0.5, 1: 0.5}, total_samples: 2050, seed: 42}
      - {class_percents: {0: 0.25, 1: 0.75}, total_samples: 2050, seed: 42}
      - {class_percents: {0: 0.1, 1: 0.9}, total_samples: 2050, seed: 42}

model_check:
  - name: french-pred
    hf_model_name: "google/gemma-2-9b-it"
    check_on: "91_eng-french"
    check_prompt: 'In one word, the statement "{prompt}" is in the language of:'
    class_names: {0: "French", 1: "English"}