run_name: "gender_experiment_gemma"
model_name: "gemma-2-9b" # 1.2 B multilignual model, 512 seq length
d_model: 3584 # 3584 for gemma-2-9b
device: "cuda:0"
cache_activations: True
seed: "42"

layers: [20] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    aggregation: "mean"
    config_name: "default_linear"
  # - name: "linear"
  #   aggregation: "mean"
  #   config_name: "default_linear"
  - name: "attention"
    aggregation: "attention"
    config_name: "default_attention"
  - name: "mass_mean"
    config_name: "default_mass_mean"
  - name: "mass_mean_iid"
    config_name: "mass_mean_iid"

# List of experiments to run
experiments:
  - name: 1-gender-pred-auc # these will rerurn og experiment 3 times, perhaps that should be avoided.
    metric: auc
    class_names: {0: "Male", 1: "Female"}
    train_on: 4_hist_fig_ismale
    evaluate_on:
      - 4_hist_fig_ismale
    score:
      - all
      - filtered
    # rebuild_config:
    #   constant_female_increasing_male:
    #     - {class_counts: {0: 50, 1: 50}, seed: 42}
    #     # - {class_counts: {0: 500, 1: 50}, seed: 42}     # 0 is French, 1 is English
    #     - {class_counts: {0: 1500, 1: 50}, seed: 42}
    #     - {class_counts: {0: 3000, 1: 50}, seed: 42}
    #     # - {class_counts: {0: 5000, 1: 50}, seed: 42}
    #     - {class_counts: {0: 7000, 1: 50}, seed: 42}
    #   constant_percent_female_increasing_total:
    #     - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 100, seed: 42}
    #     # - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 550, seed: 42}
    #     - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 1550, seed: 42}
    #     - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 3050, seed: 42}
    #     # - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 5050, seed: 42}
    #     - {class_percents: {0: 0.95, 1: 0.05}, total_samples: 7050, seed: 42}
  - name: 2-gender-pred-auc-increasing-female-fixed-total
    metric: auc
    class_names: {0: "Male", 1: "Female"}
    train_on: 4_hist_fig_ismale
    evaluate_on:
      - 4_hist_fig_ismale
    score:
      - all
      - filtered
    rebuild_config:
      increasing_female_fixed_total:
        - {class_counts: {0: 3999, 1: 1}, seed: 42}
        - {class_counts: {0: 3998, 1: 2}, seed: 42}
        - {class_counts: {0: 3995, 1: 5}, seed: 42}
        - {class_counts: {0: 3990, 1: 10}, seed: 42}
        - {class_counts: {0: 3985, 1: 15}, seed: 42}
        - {class_counts: {0: 3980, 1: 20}, seed: 42}
        - {class_counts: {0: 3975, 1: 25}, seed: 42}
        - {class_counts: {0: 3965, 1: 35}, seed: 42}
        - {class_counts: {0: 3955, 1: 45}, seed: 42}
        - {class_counts: {0: 3950, 1: 50}, seed: 42}
        - {class_counts: {0: 3900, 1: 100}, seed: 42}
        - {class_counts: {0: 3850, 1: 150}, seed: 42}
        - {class_counts: {0: 3750, 1: 250}, seed: 42}
        - {class_counts: {0: 3500, 1: 500}, seed: 42}
        - {class_counts: {0: 3250, 1: 750}, seed: 42}
  - name: 3-gender-pred-auc-llm-upsampling
    metric: auc
    class_names: {0: "Male", 1: "Female"}
    train_on: 4_hist_fig_ismale
    evaluate_on:
      - 4_hist_fig_ismale
    score:
      - all
      - filtered
    rebuild_config:
      increasing_female_fixed_total:
        - {class_counts: {0: 3999, 1: 1}, llm_upsample: False, seed: 42} # but note: we upsampled giving 5 samples to Gemini
        - {class_counts: {0: 3998, 1: 2}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3995, 1: 5}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3990, 1: 10}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3985, 1: 15}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3980, 1: 20}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3975, 1: 25}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3965, 1: 35}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3955, 1: 45}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3950, 1: 50}, llm_upsample: True, seed: 42} # not upsampled, original 50 samples
        - {class_counts: {0: 3900, 1: 100}, llm_upsample: True, seed: 42} # upsampled to 100 samples
        - {class_counts: {0: 3850, 1: 150}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3750, 1: 250}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3500, 1: 500}, llm_upsample: True, seed: 42}
        - {class_counts: {0: 3250, 1: 750}, llm_upsample: True, seed: 42}
  - name: 4-gender-pred-contrast-auc
    metric: auc
    class_names: {0: "Male", 1: "Female"}
    train_on: 4_hist_fig_ismale
    evaluate_on:
      - 4_hist_fig_ismale
    score:
      - all
      - filtered
    contrast_fn: gender_swap_contrast
    rebuild_config:
      increasing_female_fixed_total:
        - {class_counts: {0: 3999, 1: 1}, seed: 42}
        - {class_counts: {0: 3998, 1: 2}, seed: 42}
        - {class_counts: {0: 3995, 1: 5}, seed: 42}
        - {class_counts: {0: 3990, 1: 10}, seed: 42}
        - {class_counts: {0: 3985, 1: 15}, seed: 42}
        - {class_counts: {0: 3980, 1: 20}, seed: 42}
        - {class_counts: {0: 3975, 1: 25}, seed: 42}
        - {class_counts: {0: 3965, 1: 35}, seed: 42}
        - {class_counts: {0: 3955, 1: 45}, seed: 42}
        - {class_counts: {0: 3950, 1: 50}, seed: 42}
        - {class_counts: {0: 3900, 1: 100}, seed: 42}
        - {class_counts: {0: 3850, 1: 150}, seed: 42}
        - {class_counts: {0: 3750, 1: 250}, seed: 42}
        - {class_counts: {0: 3500, 1: 500}, seed: 42}
        - {class_counts: {0: 3250, 1: 750}, seed: 42}

model_check: # perhaps merge this check into experiment list as well?
  - name: gender-pred
    hf_model_name: "google/gemma-2-9b-it"
    check_on: "4_hist_fig_ismale"
    check_prompt: "In one word, {prompt}’s gender was:"
    class_names: {0: "Male", 1: "Female"}