run_name: "justice_commonsense_experiment"
model_name: "gemma-2-9b"
device: "cuda:0"
cache_activations: True
seed: "42"

layers: [20]
components:
  - "resid_post"

architectures:
  - name: "linear"
    aggregation: "mean"
    config_name: "default_linear"
  - name: "attention"
    aggregation: "attention"
    config_name: "default_attention"

experiments:
  - name: justice-cs-pred-auc
    metric: auc
    class_names: {0: "True", 1: "False"}
    train_on: justice_commonsense_train
    evaluate_on:
      - justice_commonsense_eval
    score:
      - all
    rebuild_config:
      severe_imbalance:
        - {class_counts: {0: 1000, 1: 50}, seed: 42}
        - {class_counts: {0: 5000, 1: 50}, seed: 42}
        - {class_counts: {0: 10000, 1: 50}, seed: 42}
  - name: justice-cs-pred-fpr-recall
    metric: fpr_recall
    class_names: {0: "True", 1: "False"}
    train_on: justice_commonsense_train
    evaluate_on:
      - justice_commonsense_eval
    score:
      - all
    rebuild_config:
      severe_imbalance:
        - {class_counts: {0: 1000, 1: 50}, seed: 42}
        - {class_counts: {0: 5000, 1: 50}, seed: 42}
        - {class_counts: {0: 10000, 1: 50}, seed: 42} 