run_name: "mask_llama33_70b"
model_name: "meta-llama/Llama-3.3-70B-Instruct"
device: "cuda:0" # GPU for activation extraction; sklearn probes run on CPU
cache_activations: True
log_file: "logs/mask_exp_cpu.log"
seeds: [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]

layers: [50]
components:
  - "resid_post"

# Activation extraction configuration
activation_extraction:
  format_type: "qr"  # on-policy

# Rebuild templates per-train-dataset (separate YAML anchors so each experiment can customize independently)
rebuild_config_template_98: &mask_pos_sweep_98
  increasing_pos_fixed_neg:
    - {class_counts: {0: 340, 1: 1}}
    - {class_counts: {0: 340, 1: 2}}
    - {class_counts: {0: 340, 1: 3}}
    - {class_counts: {0: 340, 1: 4}}
    - {class_counts: {0: 340, 1: 5}}
    - {class_counts: {0: 340, 1: 6}}
    - {class_counts: {0: 340, 1: 7}}
    - {class_counts: {0: 340, 1: 8}}
    - {class_counts: {0: 340, 1: 9}}
    - {class_counts: {0: 340, 1: 10}}
    - {class_counts: {0: 340, 1: 20}}
    - {class_counts: {0: 340, 1: 25}}
    - {class_counts: {0: 340, 1: 30}}
    - {class_counts: {0: 340, 1: 40}}
    - {class_counts: {0: 340, 1: 50}}

rebuild_config_template_99: &mask_pos_sweep_99
  increasing_pos_fixed_neg:
    - {class_counts: {0: 340, 1: 1}}
    - {class_counts: {0: 500, 1: 2}}
    - {class_counts: {0: 500, 1: 3}}
    - {class_counts: {0: 500, 1: 4}}
    - {class_counts: {0: 500, 1: 5}}
    - {class_counts: {0: 500, 1: 6}}
    - {class_counts: {0: 500, 1: 7}}
    - {class_counts: {0: 500, 1: 8}}
    - {class_counts: {0: 500, 1: 9}}
    - {class_counts: {0: 500, 1: 10}}
    - {class_counts: {0: 500, 1: 20}}
    - {class_counts: {0: 500, 1: 25}}
    - {class_counts: {0: 500, 1: 30}}
    - {class_counts: {0: 500, 1: 45}}

rebuild_config_template_100: &mask_pos_sweep_100
  increasing_pos_fixed_neg:
    - {class_counts: {0: 340, 1: 1}}
    - {class_counts: {0: 500, 1: 2}}
    - {class_counts: {0: 500, 1: 3}}
    - {class_counts: {0: 500, 1: 4}}
    - {class_counts: {0: 500, 1: 5}}
    - {class_counts: {0: 500, 1: 6}}
    - {class_counts: {0: 500, 1: 7}}
    - {class_counts: {0: 500, 1: 8}}
    - {class_counts: {0: 500, 1: 9}}
    - {class_counts: {0: 500, 1: 10}}
    - {class_counts: {0: 500, 1: 20}}
    - {class_counts: {0: 500, 1: 25}}
    - {class_counts: {0: 500, 1: 30}}
    - {class_counts: {0: 500, 1: 45}}

rebuild_config_template_101: &mask_pos_sweep_101
  increasing_pos_fixed_neg:
    - {class_counts: {0: 340, 1: 1}}
    - {class_counts: {0: 500, 1: 2}}
    - {class_counts: {0: 500, 1: 3}}
    - {class_counts: {0: 500, 1: 4}}
    - {class_counts: {0: 500, 1: 5}}
    - {class_counts: {0: 500, 1: 6}}
    - {class_counts: {0: 500, 1: 7}}
    - {class_counts: {0: 500, 1: 8}}
    - {class_counts: {0: 500, 1: 9}}
    - {class_counts: {0: 500, 1: 10}}
    - {class_counts: {0: 500, 1: 20}}
    - {class_counts: {0: 500, 1: 25}}
    - {class_counts: {0: 500, 1: 30}}
    - {class_counts: {0: 500, 1: 45}}

rebuild_config_template_102: &mask_pos_sweep_102
  increasing_pos_fixed_neg:
    - {class_counts: {0: 340, 1: 1}}
    - {class_counts: {0: 500, 1: 2}}
    - {class_counts: {0: 500, 1: 3}}
    - {class_counts: {0: 500, 1: 4}}
    - {class_counts: {0: 500, 1: 5}}
    - {class_counts: {0: 500, 1: 6}}
    - {class_counts: {0: 500, 1: 7}}
    - {class_counts: {0: 500, 1: 8}}
    - {class_counts: {0: 500, 1: 9}}
    - {class_counts: {0: 500, 1: 10}}
    - {class_counts: {0: 500, 1: 20}}
    - {class_counts: {0: 500, 1: 25}}
    - {class_counts: {0: 500, 1: 30}}
    - {class_counts: {0: 500, 1: 45}}

rebuild_config_template_103: &mask_pos_sweep_103
  increasing_pos_fixed_neg:
    - {class_counts: {0: 340, 1: 1}}
    - {class_counts: {0: 500, 1: 2}}
    - {class_counts: {0: 500, 1: 3}}
    - {class_counts: {0: 500, 1: 4}}
    - {class_counts: {0: 500, 1: 5}}
    - {class_counts: {0: 500, 1: 6}}
    - {class_counts: {0: 500, 1: 7}}
    - {class_counts: {0: 500, 1: 8}}
    - {class_counts: {0: 500, 1: 9}}
    - {class_counts: {0: 500, 1: 10}}
    - {class_counts: {0: 500, 1: 20}}
    - {class_counts: {0: 500, 1: 25}}
    - {class_counts: {0: 500, 1: 30}}
    - {class_counts: {0: 500, 1: 45}}

rebuild_config_template_104: &mask_pos_sweep_104
  increasing_pos_fixed_neg:
    - {class_counts: {0: 340, 1: 1}}
    - {class_counts: {0: 500, 1: 2}}
    - {class_counts: {0: 500, 1: 3}}
    - {class_counts: {0: 500, 1: 4}}
    - {class_counts: {0: 500, 1: 5}}
    - {class_counts: {0: 500, 1: 6}}
    - {class_counts: {0: 500, 1: 7}}
    - {class_counts: {0: 500, 1: 8}}
    - {class_counts: {0: 500, 1: 9}}
    - {class_counts: {0: 500, 1: 10}}
    - {class_counts: {0: 500, 1: 20}}
    - {class_counts: {0: 500, 1: 25}}
    - {class_counts: {0: 500, 1: 30}}
    - {class_counts: {0: 500, 1: 45}}

# Evaluation dataset configurations
architectures:
  - name: "sklearn_linear"
    config_name: "sklearn_linear_mean"
  - name: "sklearn_linear"
    config_name: "sklearn_linear_max"
  - name: "sklearn_linear"
    config_name: "sklearn_linear_last"
  - name: "sklearn_linear"
    config_name: "sklearn_linear_softmax"
  - name: "act_sim"
    config_name: "act_sim_mean"
  - name: "act_sim"
    config_name: "act_sim_max"
  - name: "act_sim"
    config_name: "act_sim_last"
  - name: "act_sim"
    config_name: "act_sim_softmax"

# List of experiments to run (Experiment 2 variants only)
experiments:
  - name: 2-mask-pred-auc-train-98-eval-all
    train_on: 98_mask_all_honesty
    evaluate_on:
      - 98_mask_all_honesty
      - 99_mask_continuations_honesty
      - 100_mask_disinformation_honesty
      - 101_mask_doubling_down_honesty
      - 102_mask_known_facts_honesty
      - 103_mask_provided_facts_honesty
      - 104_mask_statistics_honesty
    rebuild_config: *mask_pos_sweep_98
    on_policy: True

  - name: 2-mask-pred-auc-train-99-eval-others
    train_on: 99_mask_continuations_honesty
    evaluate_on:
      - 98_mask_all_honesty
      - 100_mask_disinformation_honesty
      - 101_mask_doubling_down_honesty
      - 102_mask_known_facts_honesty
      - 103_mask_provided_facts_honesty
      - 104_mask_statistics_honesty
    rebuild_config: *mask_pos_sweep_99
    on_policy: True

  - name: 2-mask-pred-auc-train-100-eval-others
    train_on: 100_mask_disinformation_honesty
    evaluate_on:
      - 98_mask_all_honesty
      - 99_mask_continuations_honesty
      - 101_mask_doubling_down_honesty
      - 102_mask_known_facts_honesty
      - 103_mask_provided_facts_honesty
      - 104_mask_statistics_honesty
    rebuild_config: *mask_pos_sweep_100
    on_policy: True

  - name: 2-mask-pred-auc-train-101-eval-others
    train_on: 101_mask_doubling_down_honesty
    evaluate_on:
      - 98_mask_all_honesty
      - 99_mask_continuations_honesty
      - 100_mask_disinformation_honesty
      - 102_mask_known_facts_honesty
      - 103_mask_provided_facts_honesty
      - 104_mask_statistics_honesty
    rebuild_config: *mask_pos_sweep_101
    on_policy: True

  - name: 2-mask-pred-auc-train-102-eval-others
    train_on: 102_mask_known_facts_honesty
    evaluate_on:
      - 98_mask_all_honesty
      - 99_mask_continuations_honesty
      - 100_mask_disinformation_honesty
      - 101_mask_doubling_down_honesty
      - 103_mask_provided_facts_honesty
      - 104_mask_statistics_honesty
    rebuild_config: *mask_pos_sweep_102
    on_policy: True

  - name: 2-mask-pred-auc-train-103-eval-others
    train_on: 103_mask_provided_facts_honesty
    evaluate_on:
      - 98_mask_all_honesty
      - 99_mask_continuations_honesty
      - 100_mask_disinformation_honesty
      - 101_mask_doubling_down_honesty
      - 102_mask_known_facts_honesty
      - 104_mask_statistics_honesty
    rebuild_config: *mask_pos_sweep_103
    on_policy: True

  - name: 2-mask-pred-auc-train-104-eval-others
    train_on: 104_mask_statistics_honesty
    evaluate_on:
      - 98_mask_all_honesty
      - 99_mask_continuations_honesty
      - 100_mask_disinformation_honesty
      - 101_mask_doubling_down_honesty
      - 102_mask_known_facts_honesty
      - 103_mask_provided_facts_honesty
    rebuild_config: *mask_pos_sweep_104
    on_policy: True


