run_name: "male_dataset_gemma"
model_name: "gemma-2-9b" # 1.2 B multilignual model, 512 seq length
device: "cuda:1"
cache_activations: True
seed: "42"

layers: [20] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    config_name: "default_linear"
  # - name: "attention"
  #   config_name: "default_attention"

aggregations:
  - "mean"

# List of experiments to run
experiments:
  - name: male
    train_on: 4_hist_fig_ismale
    evaluate_on:
      - 4_hist_fig_ismale
