run_name: "single_token_testing"
model_name: "gpt2" # 1.2 B multilignual model, 512 seq length
device: "cuda:1"
cache_activations: True
seed: "42"

layers: [10] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    config_name: "default_linear"
  # - name: "attention"
  #   config_name: "default_attention"

aggregations:
  - "mean"

# List of experiments to run
experiments:
  - name: letter_testing
    train_on: 92_letter
    evaluate_on:
      - 92_letter
