run_name: "spam_experiment_gemma"
model_name: "gemma-2-9b" # 1.2 B multilignual model, 512 seq length
d_model: 3584 # 3584 for gemma-2-9b
device: "cuda:1"
cache_activations: True
# seed: 42  # Old single seed format (still supported for backward compatibility)
seeds: [42]  # New multi-seed format, 43, 44, 45, 46

layers: [20] # Where SAE probes found layers peform the best
components:
  - "resid_post"

architectures:
  - name: "linear"
    config_name: "linear_mean"
  - name: "attention"
    config_name: "default_attention"


# ToDo: filtered scoring is currently broken, and I need to make sure it works for new ds's too

# List of experiments to run
experiments:
  - name: 1-spam-pred-auc
    metric: auc
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
    score:
      - all
  - name: 2-spam-pred-auc-increasing-spam-fixed-total
    metric: auc
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
      - 87_is_spam
    score:
      - all
    rebuild_config:
      increasing_spam_fixed_total:
        - {class_counts: {0: 3000, 1: 1}} # we should use all of our examples
        - {class_counts: {0: 3000, 1: 2}}
        - {class_counts: {0: 3000, 1: 5}}
        - {class_counts: {0: 3000, 1: 10}}
        - {class_counts: {0: 3000, 1: 15}}
        - {class_counts: {0: 3000, 1: 20}}
        - {class_counts: {0: 3000, 1: 25}}
        - {class_counts: {0: 3000, 1: 35}}
        - {class_counts: {0: 3000, 1: 45}}
        - {class_counts: {0: 3000, 1: 50}}
        - {class_counts: {0: 3000, 1: 100}}
        - {class_counts: {0: 3000, 1: 150}}
        - {class_counts: {0: 3000, 1: 250}}
        - {class_counts: {0: 3000, 1: 500}}
        # - {class_counts: {0: 3250, 1: 750}} don't have that many samples
  # - name: 3-spam-pred-auc-llm-upsampling
  #   metric: auc
  #   class_names: {0: "Ham", 1: "Spam"}
  #   train_on: 94_better_spam
  #   evaluate_on:
  #     - 94_better_spam
  #   score:
  #     - filtered
  #   rebuild_config:
  #     llm_upsampling_experiments:
  #       # Fixed 3000 real negative samples, variable real positive samples (1, 2, 5, 10, 15, 25)
  #       # For each positive count, train 5 probes: 1x, 2x, 3x, 4x, 5x upsampling
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 1, upsampling_factor: 1, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 1, upsampling_factor: 2, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 1, upsampling_factor: 3, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 1, upsampling_factor: 4, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 1, upsampling_factor: 5, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 2, upsampling_factor: 1, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 2, upsampling_factor: 2, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 2, upsampling_factor: 3, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 2, upsampling_factor: 4, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 2, upsampling_factor: 5, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 5, upsampling_factor: 1, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 5, upsampling_factor: 2, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 5, upsampling_factor: 3, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 5, upsampling_factor: 4, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 5, upsampling_factor: 5, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 10, upsampling_factor: 1, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 10, upsampling_factor: 2, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 10, upsampling_factor: 3, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 10, upsampling_factor: 4, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 10, upsampling_factor: 5, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 15, upsampling_factor: 1, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 15, upsampling_factor: 2, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 15, upsampling_factor: 3, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 15, upsampling_factor: 4, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 15, upsampling_factor: 5, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 25, upsampling_factor: 1, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 25, upsampling_factor: 2, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 25, upsampling_factor: 3, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 25, upsampling_factor: 4, seed: 42}
  #       - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 25, upsampling_factor: 5, seed: 42}
  # - name: 4-spam-pred-contrast-auc
  #   metric: auc
  #   class_names: {0: "Ham", 1: "Spam"}
  #   train_on: 94_better_spam
  #   evaluate_on:
  #     - 94_better_spam
  #   score:
  #     - filtered
  #   contrast_fn: spam_swap_contrast
  #   rebuild_config:
  #     increasing_spam_fixed_total:
  #       - {class_counts: {0: 3999, 1: 1}, seed: 42}
  #       - {class_counts: {0: 3998, 1: 2}, seed: 42}
  #       - {class_counts: {0: 3995, 1: 5}, seed: 42}
  #       - {class_counts: {0: 3990, 1: 10}, seed: 42}
  #       - {class_counts: {0: 3985, 1: 15}, seed: 42}
  #       - {class_counts: {0: 3980, 1: 20}, seed: 42}
  #       - {class_counts: {0: 3975, 1: 25}, seed: 42}
  #       - {class_counts: {0: 3965, 1: 35}, seed: 42}
  #       - {class_counts: {0: 3955, 1: 45}, seed: 42}
  #       - {class_counts: {0: 3950, 1: 50}, seed: 42}
  #       - {class_counts: {0: 3900, 1: 100}, seed: 42}
  #       - {class_counts: {0: 3850, 1: 150}, seed: 42}
  #       - {class_counts: {0: 3750, 1: 250}, seed: 42}
  #       - {class_counts: {0: 3500, 1: 500}, seed: 42}
  #       # - {class_counts: {0: 3250, 1: 750}, seed: 42}

model_check:
  - name: spam-pred
    hf_model_name: "google/gemma-2-9b-it"
    check_on: "94_better_spam"
    check_prompt: "Is this email spam? Answer with either Yes or No. \n {prompt}"
    class_names: {0: ["Yes", "yes", " Yes", " yes"], 1: ["No", "no", " No", " no"]}