run_name: "test_refactored"
model_name: "google/gemma-2-9b-it"
d_model: 3584
device: "cuda:0"
cache_activations: True
seeds: [42]

layers: [20]
components:
  - "resid_post"

# Activation extraction configuration
activation_extraction:
  format_type: "r"  # Options: "qr" (on-policy), "r" (off-policy instruct), "r-no-it" (off-policy non-instruct)

architectures:
  - name: "sklearn_linear"
    config_name: "sklearn_linear_mean"
  - name: "act_sim"
    config_name: "act_sim_mean"

experiments:
  - name: test-experiment
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
      - 87_is_spam
    on_policy: false

  - name: test-llm-upsampling
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
      - 87_is_spam
    on_policy: false
    rebuild_config:
      - {llm_upsampling: True, n_real_neg: 3000, n_real_pos: 4, upsampling_factor: 2}

  - name: test-imbalanced
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
      - 87_is_spam
    on_policy: false
    rebuild_config:
      - {class_counts: {0: 200, 1: 50}}

model_check:
  - name: spam-pred
    hf_model_name: "google/gemma-2-9b-it"
    check_on: ["87_is_spam", "94_better_spam"]
    method: "it"  # Options: "it" (uses chat template), "no-it" (uses few-shot prompt)
    check_prompt: "Is this email spam? Answer with either Yes or No. \n {prompt}"
    few_shot_prompt: |
      This email is spam: "Get rich quick! Make money fast with our amazing offer!"
      This email is not spam: "Hi John, here's the meeting agenda for tomorrow."
      What about this email: "{prompt}"
      Answer with either Yes or No.
    class_names: {0: ["Yes", "yes", " Yes", " yes"], 1: ["No", "no", " No", " no"]}
