run_name: "test_refactored_no_it"
model_name: "google/gemma-2-9b"
d_model: 3584
device: "cuda:0"
cache_activations: True
seeds: [42, 43]

layers: [20]
components:
  - "resid_post"

# Activation extraction configuration
activation_extraction:
  format_type: "r-no-it"  # Options: "qr" (on-policy), "r" (off-policy instruct), "r-no-it" (off-policy non-instruct)

architectures:
  - name: "sklearn_linear"
    config_name: "sklearn_linear_mean"
  - name: "act_sim"
    config_name: "act_sim_mean"
  - name: "sae_16k_l0_408_last"
    config_name: "sae_16k_l0_408_last"

experiments:
  - name: test-experiment
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
      - 87_is_spam
    on_policy: false

  - name: test-llm-upsampling
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
      - 87_is_spam
    on_policy: false
    rebuild_config:
      llm_upsampling_experiments:
        - {llm_upsampling: True, n_real_neg: 1000, n_real_pos: 4, upsampling_factor: 2}
        - {llm_upsampling: True, n_real_neg: 1000, n_real_pos: 4, upsampling_factor: 3}
        - {llm_upsampling: True, n_real_neg: 1000, n_real_pos: 4, upsampling_factor: 4}

  - name: test-imbalanced
    class_names: {0: "Ham", 1: "Spam"}
    train_on: 94_better_spam
    evaluate_on:
      - 94_better_spam
      - 87_is_spam
    on_policy: false
    rebuild_config:
      - {class_counts: {0: 200, 1: 50}}
      - {class_counts: {0: 1000, 1: 1}}

model_check:
  - name: spam-pred
    hf_model_name: "google/gemma-2-9b"
    check_on: ["87_is_spam", "94_better_spam"]
    method: "no-it"  # Options: "it" (uses chat template), "no-it" (uses few-shot prompt and no chat template)
    check_prompt: "Is this message spam? Answer with either Yes or No. \n {prompt}"
    few_shot_prompt: |
      This message is spam: "get rich quick! make money fast with our amazing offer!"
      This message is not spam: "hi john, here's the meeting agenda for tomorrow."

      What about this message: 
      "{prompt}"

      Answer with one word, either Yes or No.
    class_names: {0: ["Yes", "yes", " Yes", " yes"], 1: ["No", "no", " No", " no"]}
    # few_shot_prompt: |
    #   "get rich quick! make money fast with our amazing offer!" 
    #   This message is: spam.

    #   "hi john, here's the meeting agenda for tomorrow." 
    #   This message is: ham.

    #   "{prompt}" 
    #   This message is:
    # class_names: {0: ["Spam", "spam", " Spam", " spam"], 1: ["Ham", "ham", " Ham", " ham"]}
